### ISSUE TITLE
Improve error message for  "Resource with specified id or name already exists"

### ISSUE THREAD

**Issue by Seddryck** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#15]
When you're receiving this message, it would be extremely helpful to know if it's a vertex or an edge and what's the id that is duplicated. In case of a vertex, the label would also be useful. Would be a great improvement of usability if you could add these informations in the exception message

```
Partition range id 0 | Failed to import mini-batch. Exception was Message: {\"Errors\":[\"Encountered exception while executing function. Exception = Error: {\\\"Errors\\\":[\\\"Resource with specified id or name already exists.\\\"]}\\r\\nStack trace: Error: {\\\"Errors\\\":[\\\"Resource with specified id or name already exists.\\\"]}\\n   at createCallback (__.sys.commonBulkInsert.js:5803:26)\\n   at Anonymous function (__.sys.commonBulkInsert.js:678:29)\"]}\r\nActivityId: 7df31c7e-4779-4de5-86ac-2cf37a34cc75, Request URI: /apps/c2de8f1c-dee1-4b6c-8543-479a695c3bb2/services/6b0f2436-beac-46c1-8fb9-b6d3ee54a4c5/partitions/bae449d9-e754-4dce-87f2-a38366cf2061/replicas/131772372024487894p/, RequestStats: \r\nAddressResolution - StartTime: 2018-07-28T16:22:50.7920236Z, EndTime: 2018-07-28T16:22:50.8160522Z, TargetEndpoint: https://sportscrowding-westeurope.documents.azure.com//addresses/?$resolveFor=dbs%2f33k-AA%3d%3d%2fcolls%2f33k-AMAsXAA%3d%2fdocs&$filter=protocol eq rntbd&$partitionKeyRangeIds=0\r\n, SDK: do
cumentdb-dotnet-sdk/2.0.0 Host/32-bit MicrosoftWindowsNT/6.2.9200.0. Status code was 400, documentdb-dotnet-sdk/2.0.0 Host/32-bit MicrosoftWindowsNT/6.2.9200.0"
```

**Comment by abinav2307** [comment]
Thank you Seddryck for the feedback. 

We are currently working on a batch API as part of our SDKs and we will take this feedback to improve our error message handling as part of the new API.
